<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Prism.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ML.ApplicationLauncher.Core\ML.ApplicationLauncher.Core.csproj" />
  </ItemGroup>

</Project>
