# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build -c Release -o PublishSln
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: |
          PublishSln
          !PublishSln/**/*.pdb
    - name: Archive PDB artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdbs
        path: |
          PublishSln/**/*.pdb
  
